import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { getCategoryIcon } from "@/lib/category-icons";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { useToast } from "@/components/ui/use-toast";
import { Loader2, Save, RefreshCw, Plus, Trash2, Edit2 } from "lucide-react";
import { PageBreadcrumbs } from "@/components/PageBreadcrumbs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface CategoryPrompt {
  id: string;
  category_name: string;
  custom_prompt: string;
  use_custom_prompt: boolean;
  emoji?: string;
  category_key?: string;
}

export default function CategoryPromptsPage() {
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const [prompts, setPrompts] = useState<CategoryPrompt[]>([]);
  const [editingPrompt, setEditingPrompt] = useState<CategoryPrompt | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  useEffect(() => {
    loadCategories();
  }, []);

  const loadCategories = async () => {
    try {
      setLoading(true);
      
      const { data, error } = await supabase
        .from('category_prompts')
        .select('*')
        .order('category_name');

      if (error) throw error;

      setPrompts(data || []);
    } catch (error: any) {
      console.error('Error loading prompts:', error);
      toast({
        title: "Помилка",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (promptId: string, prompt: string, useCustom: boolean) => {
    try {
      setSaving(promptId);
      
      const { error } = await supabase
        .from('category_prompts')
        .update({
          custom_prompt: prompt,
          use_custom_prompt: useCustom,
        })
        .eq('id', promptId);

      if (error) throw error;

      toast({
        title: "Успішно",
        description: "Промт збережено",
      });
      
      await loadCategories();
    } catch (error: any) {
      console.error('Error saving:', error);
      toast({
        title: "Помилка",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setSaving(null);
    }
  };

  const handleEdit = (prompt: CategoryPrompt) => {
    setEditingPrompt(prompt);
    setIsDialogOpen(true);
  };

  const handleSaveDialog = async () => {
    if (!editingPrompt) return;
    
    // Validate
    if (!editingPrompt.category_name.trim()) {
      toast({
        title: "Помилка",
        description: "Назва категорії обов'язкова",
        variant: "destructive",
      });
      return;
    }
    
    if (!editingPrompt.custom_prompt.trim()) {
      toast({
        title: "Помилка",
        description: "Промт обов'язковий",
        variant: "destructive",
      });
      return;
    }
    
    try {
      setSaving(editingPrompt.id || 'new');
      
      if (editingPrompt.id) {
        // Update existing
        const updateData: any = {
          category_name: editingPrompt.category_name,
          custom_prompt: editingPrompt.custom_prompt,
          use_custom_prompt: editingPrompt.use_custom_prompt,
        };
        
        // Add emoji if provided
        if (editingPrompt.emoji && editingPrompt.emoji.trim()) {
          updateData.emoji = editingPrompt.emoji.trim();
        }
        
        // Add category_key if provided
        if (editingPrompt.category_key && editingPrompt.category_key.trim()) {
          updateData.category_key = editingPrompt.category_key.trim();
        }
        
        const { error } = await supabase
          .from('category_prompts')
          .update(updateData)
          .eq('id', editingPrompt.id);

        if (error) throw error;
      } else {
        // Create new
        const insertData: any = {
          category_name: editingPrompt.category_name,
          custom_prompt: editingPrompt.custom_prompt,
          use_custom_prompt: editingPrompt.use_custom_prompt,
        };
        
        // Add emoji if provided
        if (editingPrompt.emoji && editingPrompt.emoji.trim()) {
          insertData.emoji = editingPrompt.emoji.trim();
        }
        
        // category_key will be auto-generated by trigger
        
        const { error } = await supabase
          .from('category_prompts')
          .insert(insertData);

        if (error) throw error;
      }

      toast({
        title: "Успішно",
        description: editingPrompt.id ? "Промт оновлено" : "Категорію створено",
      });
      
      await loadCategories();
      setIsDialogOpen(false);
      setEditingPrompt(null);
    } catch (error: any) {
      console.error('Error saving:', error);
      toast({
        title: "Помилка",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setSaving(null);
    }
  };

  const updatePromptField = (field: keyof CategoryPrompt, value: any) => {
    if (editingPrompt) {
      setEditingPrompt({ ...editingPrompt, [field]: value });
    }
  };

  const resetToDefault = async (promptId: string, categoryName: string) => {
    const defaultPrompt = `Створи цікавий пост на тему "${categoryName}". Пост має бути інформативним, залучаючим та корисним для читачів. Використовуй простою і зрозумілу мову.`;
    
    await handleSave(promptId, defaultPrompt, false);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6 p-4 md:p-6">
      <PageBreadcrumbs />
      
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl md:text-3xl font-bold">Промти категорій</h2>
          <p className="text-sm md:text-base text-muted-foreground mt-2">
            Налаштування промтів для кожної категорії AI генерації
          </p>
        </div>
        
        <div className="flex gap-2">
          <Button
            onClick={() => {
              setEditingPrompt({
                id: '',
                category_name: '',
                custom_prompt: '',
                use_custom_prompt: false,
                emoji: '',
                category_key: ''
              });
              setIsDialogOpen(true);
            }}
            className="shrink-0"
          >
            <Plus className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Додати категорію</span>
            <span className="sm:hidden">Додати</span>
          </Button>
          
          <Button
            onClick={loadCategories}
            variant="outline"
            size="icon"
            disabled={loading}
            className="shrink-0"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:gap-6">
        {prompts.map((prompt) => (
          <Card key={prompt.id} className="p-4 md:p-6 glass-effect border-border/50">
            <div className="space-y-4">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    {getCategoryIcon(prompt.emoji, "w-8 h-8")}
                    <h3 className="text-lg font-bold">{prompt.category_name}</h3>
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">
                    {prompt.use_custom_prompt 
                      ? "Використовується кастомний промт" 
                      : "Використовується дефолтний промт"}
                  </p>
                  {prompt.category_key ? (
                    <p className="text-xs text-muted-foreground mt-1">
                      Ключ: <code className="bg-muted px-1 py-0.5 rounded">{prompt.category_key}</code>
                    </p>
                  ) : (
                    <p className="text-xs text-destructive mt-1">
                      ⚠️ Відсутній ключ категорії
                    </p>
                  )}
                </div>
                
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-2">
                    <Label htmlFor={`switch-${prompt.id}`} className="text-sm">
                      Кастомний
                    </Label>
                    <Switch
                      id={`switch-${prompt.id}`}
                      checked={prompt.use_custom_prompt}
                      onCheckedChange={(checked) =>
                        handleSave(prompt.id, prompt.custom_prompt, checked)
                      }
                      disabled={saving === prompt.id}
                    />
                  </div>
                </div>
              </div>

              <Separator />

              <div className="space-y-2">
                <Label className="text-sm font-medium">Промт</Label>
                <div className="relative">
                  <Textarea
                    value={prompt.custom_prompt}
                    readOnly
                    className="min-h-[100px] resize-none bg-muted/50 cursor-pointer"
                    onClick={() => handleEdit(prompt)}
                  />
                  <Button
                    size="sm"
                    variant="ghost"
                    className="absolute top-2 right-2"
                    onClick={() => handleEdit(prompt)}
                  >
                    <Edit2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>

              <div className="flex gap-2">
                <Button
                  onClick={() => handleEdit(prompt)}
                  variant="outline"
                  className="flex-1"
                  disabled={saving === prompt.id}
                >
                  <Edit2 className="w-4 h-4 mr-2" />
                  Редагувати
                </Button>
                
                <Button
                  onClick={() => resetToDefault(prompt.id, prompt.category_name)}
                  variant="outline"
                  disabled={saving === prompt.id}
                  title="Скинути до дефолту"
                >
                  {saving === prompt.id ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <RefreshCw className="w-4 h-4" />
                  )}
                </Button>
                
                <Button
                  onClick={async () => {
                    if (confirm(`Видалити категорію "${prompt.category_name}"?`)) {
                      try {
                        setSaving(prompt.id);
                        const { error } = await supabase
                          .from('category_prompts')
                          .delete()
                          .eq('id', prompt.id);
                        
                        if (error) throw error;
                        
                        toast({
                          title: "Успішно",
                          description: "Категорію видалено",
                        });
                        
                        await loadCategories();
                      } catch (error: any) {
                        toast({
                          title: "Помилка",
                          description: error.message,
                          variant: "destructive",
                        });
                      } finally {
                        setSaving(null);
                      }
                    }
                  }}
                  variant="outline"
                  disabled={saving === prompt.id}
                  className="text-destructive hover:bg-destructive/10"
                  title="Видалити категорію"
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Edit Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[700px]">
          <DialogHeader>
            <DialogTitle>Редагувати промт: {editingPrompt?.category_name}</DialogTitle>
            <DialogDescription>
              Налаштуйте промт для генерації контенту в цій категорії
            </DialogDescription>
          </DialogHeader>
          
          {editingPrompt && (
            <div className="space-y-4 py-4">
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="category-name">Назва категорії</Label>
                  <Input
                    id="category-name"
                    value={editingPrompt.category_name}
                    onChange={(e) => updatePromptField('category_name', e.target.value)}
                    placeholder="наприклад: Технології, Спорт, Музика..."
                    disabled={!!editingPrompt.id}
                  />
                  {!editingPrompt.id && (
                    <p className="text-xs text-muted-foreground">
                      Ключ генерується автоматично з назви
                    </p>
                  )}
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="emoji">Емодзі (опціонально)</Label>
                  <Input
                    id="emoji"
                    value={editingPrompt.emoji || ''}
                    onChange={(e) => updatePromptField('emoji', e.target.value)}
                    placeholder="📝 (за замовчуванням)"
                    maxLength={2}
                  />
                  <p className="text-xs text-muted-foreground">
                    Залиш пустим для 📝 за замовчуванням
                  </p>
                </div>
                
                {editingPrompt.id && (
                  <div className="space-y-2">
                    <Label htmlFor="category-key">Ключ категорії</Label>
                    <Input
                      id="category-key"
                      value={editingPrompt.category_key || ''}
                      onChange={(e) => updatePromptField('category_key', e.target.value)}
                      placeholder="наприклад: technology, sport, music..."
                    />
                    <p className="text-xs text-muted-foreground">
                      Унікальний ідентифікатор категорії (латинські літери, цифри, підкреслення)
                    </p>
                  </div>
                )}
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="prompt">Промт</Label>
                <Textarea
                  id="prompt"
                  value={editingPrompt.custom_prompt}
                  onChange={(e) => updatePromptField('custom_prompt', e.target.value)}
                  className="min-h-[200px] resize-y"
                  placeholder="Введіть промт для AI генерації..."
                />
                <p className="text-xs text-muted-foreground">
                  Підказка: Використовуйте чіткі інструкції, щоб AI краще розумів що потрібно згенерувати
                </p>
              </div>

              <div className="flex items-center space-x-2">
                <Switch
                  id="use-custom"
                  checked={editingPrompt.use_custom_prompt}
                  onCheckedChange={(checked) => updatePromptField('use_custom_prompt', checked)}
                />
                <Label htmlFor="use-custom" className="text-sm">
                  Використовувати цей промт для генерації
                </Label>
              </div>
            </div>
          )}
          
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setIsDialogOpen(false);
                setEditingPrompt(null);
              }}
            >
              Скасувати
            </Button>
            <Button onClick={handleSaveDialog} disabled={saving !== null}>
              {saving ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Збереження...
                </>
              ) : (
                <>
                  <Save className="w-4 h-4 mr-2" />
                  Зберегти
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
